name = "smartlamp-backend"
main = "src/index.ts"
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]

[vars]
COOKIE_SECURE = "false"
COOKIE_SAME_SITE = "Strict"
CORS_ORIGINS = "http://127.0.0.1:5173,http://localhost:5173"
MQTT_CLIENT_ID_PREFIX = "smartlamp-worker"
JWT_ACCESS_TTL_SEC = "900"
JWT_REFRESH_TTL_SEC = "2592000"
AUTH_LOGIN_RATE_LIMIT_MAX = "8"
AUTH_LOGIN_RATE_LIMIT_WINDOW_SEC = "60"
COMMAND_SIGN_RATE_LIMIT_MAX = "30"
COMMAND_SIGN_RATE_LIMIT_WINDOW_SEC = "60"
SEED_ADMIN_EMAIL = "admin"
SEED_SAMPLE_DEVICE_ID = "lampu-ruang-tamu"

[[d1_databases]]
binding = "DB"
database_name = "smartlamp_db"
database_id = "71be5235-fd72-4fb3-a646-b6a07e92b1d5"

[triggers]
crons = ["* * * * *"]
